const FETCH_ARTICLES = 'FETCH_ARTICLES';

const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';

const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export { FETCH_ARTICLES, FETCH_ARTICLES_SUCCESS, FETCH_ARTICLES_ERROR };
